version: "3.9"

services:
  orders-postgres:
    image: postgres:16
    container_name: orders-postgres
    environment:
      POSTGRES_USER: orders_user
      POSTGRES_PASSWORD: orders_password
      POSTGRES_DB: orders_db
    ports:
      - "5433:5432"
    volumes:
      - orders_postgres_data:/var/lib/postgresql/data

volumes:
  orders_postgres_data:
